video:
  realpath: D:\\java\\IdeaProjects\\cdzq-study\\target\\video\\
  abspath: http://192.168.61.39:8080/video/
image:
  realpath: D:\\java\\IdeaProjects\\cdzq-study\\target\\image\\
  abspath: http://192.168.61.39:8080/image/
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
